### ISSUE TITLE
Docker-compose: ImportError: No module named 'base'

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Seeder#226]
Čéšť, neupravil jsi nějak local-settings.py? V template nic nového není a tohle mi hásí Seeder při buildu pomocí docker-compose.

Step 7 : RUN python3 /code/Seeder/manage.py collectstatic --noinput
 ---> Running in f58b4806c8c3
Traceback (most recent call last):
  File "/code/Seeder/manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/code/Seeder/settings/local_settings.py", line 1, in <module>
    from base import *
ImportError: No module named 'base'

**Comment by Visgean** [comment]
https://github.com/WebArchivCZ/Seeder/commit/2c06a0beecb66b88664fbc07b6d3171dedd5e6c1 zmigroval jsem na py3. Budes taky muset rebuildnout machinu - ``docker-compose build``. Pridal jsem taky nejake bash scripty pro snadnejsi ovladani compose...
