### ISSUE TITLE
Problém s deploymentem

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Seeder#252]
Současný build mi nejde deploynout ani manuálně ani pomocí fabric - postupuji dle: https://seeder.readthedocs.io/en/latest/deploying.html

(seeder)[rudolf@curator02 Seeder]$ fab deploy_locally
Fatal error: Couldn't find any fabfiles!

...
(seeder)[rudolf@curator02 Seeder]$ ./manage.py migrate
Traceback (most recent call last):
```
  File "./manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/Seeder/Seeder/urls.py", line 11, in <module>
    from source import views as source_views
  File "/opt/Seeder/Seeder/source/views.py", line 18, in <module>
    from . import forms, models, tables, field_filters
  File "/opt/Seeder/Seeder/source/forms.py", line 11, in <module>
    class SourceForm(forms.ModelForm):
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/django/forms/models.py", line 247, in __new__
    opts.field_classes)
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/django/forms/models.py", line 172, in fields_for_model
    formfield = f.formfield(**kwargs)
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/django/db/models/fields/related.py", line 945, in formfield
    'queryset': self.remote_field.model._default_manager.using(db),
  File "/opt/virtualenv/seeder/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/Seeder/Seeder/publishers/models.py", line 16, in get_queryset
    return super().get_queryset().filter(active=True)
TypeError: Error when calling the metaclass bases
    super() takes at least 1 argument (0 given)
```

**Comment by Visgean** [comment]
Pouzivas starou verzi pythonu, budes muset smaznout ten stary a vytvorit novy na zaklade pythonu3:

mkvirtualenv seeder -p /usr/bin/python3.5

**Comment by westfood** [comment]
Musím mit nainstalovaný python 3.5? Nestačí python 3.4?

**Comment by Visgean** [comment]
ten by mel stacit

**Comment by Visgean** [comment]
jinak ten fabric uz jsem smaznul a presunul jsem to do:
https://github.com/WebArchivCZ/Seeder/blob/master/Seeder/prepare.sh
https://github.com/WebArchivCZ/Seeder/blob/master/Seeder/pull_locales.sh

**Comment by westfood** [comment]
hele a při spuštění migrate, tohle je cajk?

Applying contracts.0013_auto_20160422_1000.../opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/models/fields/__init__.py:1453: RuntimeWarning: DateTimeField Contract.created received a naive datetime (2016-05-26 21:19:14.176228) while time zone support is active.
  RuntimeWarning)

**Comment by Visgean** [comment]
jj, to je jenom warning ze ignoruju casovou zonu
