### ISSUE TITLE
uwsgi

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Seeder#255]
Blbne mi uwsgi, nevíš co s tím? Nevidí to settings, ač je vše správně deploynutý.

```
[uWSGI] getting INI configuration from seeder.ini
*** Starting uWSGI 2.0.12 (64bit) on [Thu Jun  2 15:44:57 2016] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-4) on 02 January 2016 19:52:54
os: Linux-3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015
nodename: curator02.webarchiv.cz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /etc/uwsgi.d
writing pidfile to /opt/Seeder/seeder.pid
detected binary path: /usr/sbin/uwsgi
your processes number limit is 1875
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers ***
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /opt/Seeder/seeder.sock fd 3
Python version: 3.4.3 (default, Jan 26 2016, 02:25:35)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
Set PythonHome to /opt/virtualenv/seeder
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1ee96b0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 509376 bytes (497 KB) for 6 cores
*** Operational MODE: preforking ***
added /opt/Seeder/ to pythonpath.
Traceback (most recent call last):
  File "/opt/Seeder/Seeder/wsgi.py", line 14, in <module>
    application = get_wsgi_application()
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/virtualenv/seeder/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'settings'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
```
uwsgi emperor
```
[uwsgi]
uid = uwsgi
gid = uwsgi
pidfile = /run/uwsgi/uwsgi.pid
emperor = /etc/uwsgi.d
stats = /run/uwsgi/stats.sock
emperor-tyrant = false
cap = setgid,setuid
```

uwsgi pro seeder
```
[uwsgi]
virtualenv      = /opt/virtualenv/seeder
pythonpath      = /opt/Seeder
plugins         = python3
master          = 1
pidfile         = /opt/Seeder/seeder.pid
touch-reload    = /opt/Seeder/reload.touch
socket          = /opt/Seeder/seeder.sock
chmod-socket    = 777
cheaper-algo    = spare
cheaper         = 2
cheaper-initial = 2
cheaper-step    = 1
processes       = 6
vacuum          = 1
harakiri        = 60
wsgi-file       = /opt/Seeder/Seeder/wsgi.py
```

**Comment by westfood** [comment]
pythonpath směřuje přímo na app, tj.  = /opt/Seeder/Seeder
