### ISSUE TITLE
Dokumentace

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Seeder#256]
Vypadá to na nějakou uniklou závislost, ale závislosti mi připadaj v cajku.. Není problém, že MySQLdb není pro Python3?

```
Traceback (most recent call last):
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/backends/mysql/base.py", line 25, in <module>
    import MySQLdb as Database
ImportError: No module named 'MySQLdb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 165, in __call__
    signals.request_started.send(sender=self.__class__, environ=environ)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/__init__.py", line 55, in reset_queries
    for conn in connections.all():
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/utils.py", line 227, in all
    return [self[alias] for alias in self]
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/utils.py", line 227, in <listcomp>
    return [self[alias] for alias in self]
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/utils.py", line 212, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/utils.py", line 116, in load_backend
    return import_module('%s.base' % backend_name)
  File "/opt/virtualenv/seeder/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/backends/mysql/base.py", line 28, in <module>
    raise ImproperlyConfigured("Error loading MySQLdb module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named 'MySQLdb'
```

**Comment by Visgean** [comment]
tohle resi zavislost v pip3 pymysql, ta je v requirements

**Comment by westfood** [comment]
mám ji nainstalovanou a stejně mi vrací tuhle chybu.

**Comment by westfood** [comment]
```
(seeder) [rudolf@curator02 seeder]$ pip show pymysql
---
Metadata-Version: 2.0
Name: PyMySQL
Version: 0.7.4
Summary: Pure Python MySQL Driver
Home-page: https://github.com/PyMySQL/PyMySQL/
Author: INADA Naoki
Author-email: songofacandy@gmail.com
Installer: pip
License: MIT
Location: /opt/virtualenv/seeder/lib/python3.4/site-packages
Requires:
Classifiers:
  Development Status :: 5 - Production/Stable
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: Implementation :: CPython
  Programming Language :: Python :: Implementation :: PyPy
  Intended Audience :: Developers
  License :: OSI Approved :: MIT License
  Topic :: Database
```

**Comment by Visgean** [comment]
zkus pip3 install pymysql a pak overit jestli je tam libmysqlclient-dev

**Comment by westfood** [comment]
chyběl pip: mysqlclient - asi by to bylo dobrý přidat do requirements.txt, ale nevím jestli to pro změnu nezbortí ubuntu build.. ale pip repo je asi všude stejný, ne?

**Comment by Visgean** [comment]
No to je jina knihovna ktera poskytuje stejny rozhrani, nevim ted je v tom trochu bordel. Klidne muzeme pouzivat tu pymsql, ono se to stejne pouzije jenom na ten import.

**Comment by westfood** [comment]
pymysql mám koretkně nainstalovaný, ale nefunguje.. 

někde jsem dohleda:
```
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass
```

stáčí dát vědět v dokumentaci, že když nefunguje je pymysql, může se použít mysqlclient..

**Comment by westfood** [comment]
Vezmu to jinak, budeš se ještě vracet k dokumentaci nebo je to úkol na mně do budoucna?

**Comment by Visgean** [comment]
https://github.com/WebArchivCZ/Seeder/blob/master/Seeder/manage.py ... 

dokumentaci jeste budu resit, ale za celou dobu se to nasazeni zmenilo tolikrat ze proste uz se v tom ztracim a nevim jak to nasazujete, myslel jsem ze to bude v docker kontajneru zalozenem na ubuntu kde by to melo fungovat stejne jako mi to funguje v tom compose... Takze co se tyce te dokumentace tak by stejne bylo lepsi aby si to zcasti toho deploymentu upravovali i ty = ja nevim co vy potkate pri vasem setupu...

**Comment by Visgean** [comment]
Ted ti to teda funguje?

**Comment by westfood** [comment]
Ještě řeším mail backend a nějakej trabl s nodejs/manet, ale import legacy_dbs proběhl, fulltext search funguje.

Ad dokumentace jak ve vedlejším issue.. 

Dockerfile akceptuju jako instalační dokumentaci. Já mám skoro hotovej ansible-playbook jako instalační dokumetnaci k CentOS. Spíš se bude hodit programátorská dokumentace a info jak funguje legacy_sync - např. stačí nahrát sql.dump do složky, nebo jestli je potřeba i nahodit mysql dbs. Ve finále jde o to aby admin věděl manage create superuser, co dělají ty příkazy v crontabu - co by neměl nikdy dělat (či který příkazy nejsou idempotentní) a co by naopak měl někdy dělat .

**Comment by westfood** [comment]
Čekám mně ještě sentry a pak ten autobuild..

**Comment by Visgean** [comment]
OK, hele kdyztak mi pak nahazej issues k jednotlivym vecem co chces abych do dokumentace sepsal.

**Comment by westfood** [comment]
ok
