### ISSUE TITLE
manage.py migrate hází chybu

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Seeder#279]
Ahoj,

manage.py mi hází: 
```
"  main_url = forms.URLField(_('Main URL'))
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/forms/fields.py", line 233, in __init__
    self.validators.append(validators.MaxLengthValidator(int(max_length)))
TypeError: int() argument must be a string, a bytes-like object or a number, not '__proxy__'"
```
nemá to nějakou souvislost s: https://github.com/WebArchivCZ/Seeder/commit/215dc03eaf89a40a07b227424abd2e4b6a018e3c ?

```
(seeder) [rudolf@seeder Seeder]$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/virtualenv/seeder/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/Seeder/Seeder/urls.py", line 11, in <module>
    from source import views as source_views
  File "/opt/Seeder/Seeder/source/views.py", line 18, in <module>
    from . import forms, models, tables, field_filters
  File "/opt/Seeder/Seeder/source/forms.py", line 11, in <module>
    class SourceForm(forms.ModelForm):
  File "/opt/Seeder/Seeder/source/forms.py", line 20, in SourceForm
    main_url = forms.URLField(_('Main URL'))
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/forms/fields.py", line 233, in __init__
    self.validators.append(validators.MaxLengthValidator(int(max_length)))
TypeError: int() argument must be a string, a bytes-like object or a number, not '__proxy__'
```

**Comment by Visgean** [comment]
Proverim...
