### ISSUE TITLE
Sentry is not working my friend.

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Seeder#327]
```
Bad Request (400)
```

**Comment by westfood** [comment]
Hele není nějaký trabl s raven/sentry? // sentry mi běží, ale ta integrace nefachá..

```
(seeder) bash-4.2$ python manage.py raven test
Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/opt/virtualenv/seeder/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/raven/contrib/django/management/commands/raven.py", line 17, in <module>
    class Command(BaseCommand):
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/raven/contrib/django/management/commands/raven.py", line 20, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

**Comment by Visgean** [comment]
ok checknu a pripadne upgradnu

**Comment by Visgean** [comment]
ok upgrade v 8c40f021322df800ee6966bd791cc6086a9ec03d

**Comment by westfood** [comment]
Done!
