### ISSUE TITLE
manage.py padne i s python 3.4

### ISSUE THREAD

**Issue by westfood** [WebarchivCZ/Seeder#352]
```
(seeder) [root@war Seeder]# git log -1
commit cbff7aa9eadbe5b6b2898fb801289f8e10a33d7a
Author: Visgean Skeloru <me@visgean.me>
Date:   Mon Feb 20 17:44:30 2017 +0000

    python3.4 support

    fixes #349
```
```
(seeder) [root@war Seeder]# python -V
Python 3.4.3
```
```
(seeder) [root@war Seeder]# Seeder/manage.py migrate
Traceback (most recent call last):
  File "Seeder/manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/virtualenv/seeder/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/Seeder/Seeder/urls.py", line 20, in <module>
    from www import views as www_views
  File "/opt/Seeder/Seeder/www/views.py", line 283
    **super().get_context_data()
     ^
SyntaxError: invalid syntax
(seeder) [root@war Seeder]#
```

**Comment by Visgean** [comment]
Asi jsem jeste jednu prehlidl...
