### ISSUE TITLE
./manage.py migrate

### ISSUE THREAD

**Issue by westfood** [WebarchivCZ/Seeder#409]
```
(seeder) [rudolf@war Seeder]$ ./manage.py migrate
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'legacy_seeder'
        HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.10/ref/databases/#mysql-sql-mode
Traceback (most recent call last):
  File "./manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/migrations/loader.py", line 268, in build_graph
    raise exc
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/migrations/loader.py", line 238, in build_graph
    self.graph.validate_consistency()
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/migrations/graph.py", line 261, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/migrations/graph.py", line 261, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/migrations/graph.py", line 104, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration www.0007_merge_20170315_1002 dependencies reference nonexistent parent node ('www', '0006_auto_20170310_2350')
```

**Comment by Visgean** [comment]
Vymazal si celou databazi a nas cisty git? Tohle vypada na merge migraci kterou ja u sebe nemam, kdyztak dej git status a smaz ty migrace co nejsou v repu.

**Comment by westfood** [comment]
nene, ještě nemám čistou databázi.. čekám na pokyn

**Comment by Visgean** [comment]
no tak mej :) vcera jsem to psal Jardovy...

**Comment by westfood** [comment]
cajk, resetuju bázi

**Comment by westfood** [comment]
vypadá cajk
