### ISSUE TITLE
./manage.py search_blob_initialize

### ISSUE THREAD

**Issue by westfood** [WebarchivCZ/Seeder#410]
```
(seeder) [rudolf@war Seeder]$ ./manage.py search_blob_initialize
Traceback (most recent call last):
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column source_source.dead_source does not exist
LINE 1: ...."screenshot", "source_source"."screenshot_date", "source_so...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/opt/Seeder/Seeder/search_blob/management/commands/search_blob_initialize.py", line 12, in handle
    for s in Source.objects.all():
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column source_source.dead_source does not exist
LINE 1: ...."screenshot", "source_source"."screenshot_date", "source_so...
```

**Comment by westfood** [comment]
```
(seeder) [rudolf@war opt]$ Seeder/Seeder/manage.py search_blob_initialize
Traceback (most recent call last):
  File "Seeder/Seeder/manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/opt/Seeder/Seeder/search_blob/management/commands/search_blob_initialize.py", line 13, in handle
    s.update_search_blob()
  File "/opt/Seeder/Seeder/search_blob/models.py", line 75, in update_search_blob
    "blob": blob_all
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/models/query.py", line 488, in update_or_create
    obj = self.get(**lookup)
  File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/models/query.py", line 389, in get
    (self.model._meta.object_name, num)
search_blob.models.MultipleObjectsReturned: get() returned more than one Blob -- it returned 2!
```

**Comment by Visgean** [comment]
hmm, muzes dat ./manage.py reset search_blob a pak znova to initialize? myslim ze tam byla nekde chyba s tim jak to spadlo.

**Comment by Visgean** [comment]
Ale jestli se to deje normalne tak to opravim.

**Comment by westfood** [comment]
to bylo druhé spuštění po čisté instalaci..

**Comment by Visgean** [comment]
hmm ok.

**Comment by Visgean** [comment]
pushnul jsem, prosim o test.

**Comment by westfood** [comment]
vypadá cajk
