### ISSUE TITLE
docker-compose link na elastic

### ISSUE THREAD

**Issue by westfood** [WebarchivCZ/Seeder#429]
Hele, 

jaktože ti fungujou buildy když máš v docker compose link na nedefinovanej elastic?

**Comment by westfood** [comment]
+ když odstraním elastic link

...
Step 6 : RUN python3 /code/Seeder/manage.py collectstatic --noinput
 ---> Running in a93b7fe17ba6
Traceback (most recent call last):
  File "/code/Seeder/manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.5/dist-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.5/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.5/dist-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'settings.local_settings'
ERROR: Service 'web' failed to build: The command '/bin/sh -c python3 /code/Seeder/manage.py collectstatic --noinput' returned a non-zero code: 1
...

**Comment by Visgean** [comment]
Ja jsem se na ten compose vykaslal, je to hrozne slozity na debugovani.
